name: Integration tests

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+'
  pull_request: ~

jobs:
  integration-tests:
    runs-on: "ubuntu-20.04"
    timeout-minutes: 5
    permissions:
      packages: read
      contents: read

    services:
      solr:
        image: ghcr.io/ibexa/product-catalog/solr:latest
        ports:
          - 8983
        options: >-
          --health-cmd "solr status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    strategy:
      fail-fast: false
      matrix:
        php:
          - '7.4'
          - '8.0'
          - '8.1'
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: pdo_sqlite, gd
          tools: cs2pr

      - uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "highest"

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Setup Solr
        run: bin/.travis/init_solr.sh
        env:
          CORES_SETUP: single
          SOLR_CORES: collection1

      - name: Run integration test suite on Solr
        run: composer run-script --timeout=600 test -- --testsuite integration --exclude-group solr-incomplete
        env:
          SEARCH_ENGINE: solr
          SOLR_DSN: http://localhost:${{ job.services.solr.ports[8983] }}/solr
          SOLR_CORE: collection1