name: Solr integration tests

on:
    push:
        branches:
            - '[0-9]+.[0-9]+'
    pull_request: ~

jobs:
    solr-integration:
        name: "Integration tests"
        runs-on: "ubuntu-26.04"
        strategy:
            fail-fast: false
            matrix:
                solr-version:
                    - '7.7.3'
                    - '8.11.2'
                    - '9.8.1'
                cores-setup:
                    - 'dedicated'
                    - 'shared'
                    - 'single'
                    - 'cloud'
                include:
                    # Solr 7.x uses the CMS garbage collector, removed in Java 14
                    - solr-version: '7.7.3'
                      java-version: '11'
                    - solr-version: '8.11.2'
                      java-version: '17'
                    - solr-version: '9.8.1'
                      java-version: '17'
        env:
            CORES_SETUP: ${{ matrix.cores-setup }}
            SOLR_VERSION: ${{ matrix.solr-version }}
        steps:
            - if: matrix.cores-setup == 'cloud'
              name: "Set up Solr Cloud"
              run: echo "SOLR_CLOUD=yes" >> $GITHUB_ENV

            - if: matrix.cores-setup == 'single'
              name: "Set up single core"
              run: echo "SOLR_CORES=collection1" >> $GITHUB_ENV

            - uses: actions/checkout@v7

            -   name: Install Composer dependencies
                uses: ibexa/gh-workflows/actions/composer-install@main
                with:
                    php-version: '7.4'
                    gh-client-id: ${{ secrets.AUTOMATION_CLIENT_ID }}
                    gh-client-secret: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
                    satis-network-key: ${{ secrets.SATIS_NETWORK_KEY }}
                    satis-network-token: ${{ secrets.SATIS_NETWORK_TOKEN }}

            - name: Set up Java
              uses: actions/setup-java@v6
              with:
                  distribution: 'temurin'
                  java-version: ${{ matrix.java-version }}

            - name: Init Solr
              run: ./.github/init_solr.sh

            - name: Run integration test suite
              run: composer test-integration-solr
