name: Solr 9 Integration Test (PR only)

on:
    push:
        branches:
            - main
            - '[0-9]+.[0-9]+'
    pull_request: ~

jobs:
    solr9-test:
        name: "Solr 9.8.1 PR Test"
        runs-on: ubuntu-22.04
        strategy:
            fail-fast: false
            matrix:
                cores-setup:
                    - 'dedicated'
                    - 'shared'
                    - 'single'
                    - 'cloud'
        env:
            CORES_SETUP: ${{ matrix.cores-setup }}
            SOLR_VERSION: '9.8.1'

        steps:
            - if: matrix.cores-setup == 'cloud'
              name: "Set up Solr Cloud"
              run: echo "SOLR_CLOUD=yes" >> $GITHUB_ENV

            - if: matrix.cores-setup == 'single'
              name: "Set up single core"
              run: echo "SOLR_CORES=collection1" >> $GITHUB_ENV

            - uses: actions/checkout@v3

            - name: Setup PHP Action
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  coverage: none

            - uses: ramsey/composer-install@v2
              with:
                  dependency-versions: highest

            - name: Init Solr
              run: ./.github/init_solr.sh

            - name: Run integration test suite
              run: composer test-integration-solr
